"""Build GitHub-renderable previews of the deck from the QA captures.

GitHub cannot render the Reveal.js HTML inline, so this writes PNG thumbnails of
every slide (final fragment state), one overview contact sheet, and a gallery in
presentation/README.md that links each thumbnail to the live GitHub Pages deck.

Run after `npm test` (which produces qa/1280x720 captures): `npm run preview`.
"""
import html
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
QA = ROOT / "qa" / "1280x720"
OUT = ROOT / "preview"
SLIDES_OUT = OUT / "slides"
README = ROOT / "README.md"
LIVE = "https://martinopedal.github.io/squad-terraform-session-2026-10-14/presentation/"
START, END = "<!-- preview:start -->", "<!-- preview:end -->"
THUMB = (480, 270)
SHEET_CELL, SHEET_COLS, GAP = (320, 180), 6, 8


def final_captures():
    order = re.findall(r'<section id="([^"]+)"', (ROOT / "index.html").read_text(encoding="utf-8"))
    files = list(QA.glob("*-f*.png"))
    if not files:
        return []
    # Only the latest QA run: older runs may use different slide numbering.
    newest = max(p.stat().st_mtime for p in files)
    latest = {}
    for path in files:
        m = re.match(r"^\d+-(.+)-f(\d+)\.png$", path.name)
        if not m or path.stat().st_mtime < newest - 900:
            continue
        slide_id, fragment = m.group(1), int(m.group(2))
        if slide_id not in latest or fragment > latest[slide_id][0]:
            latest[slide_id] = (fragment, path)
    missing = [sid for sid in order if sid not in latest]
    if missing:
        sys.exit(f"QA captures missing for {missing}; rerun npm test.")
    return [(i + 1, sid, latest[sid][1]) for i, sid in enumerate(order)]


def titles():
    source = (ROOT / "index.html").read_text(encoding="utf-8")
    found = {}
    for m in re.finditer(r'<section id="([^"]+)"[^>]*?(?:aria-labelledby="[^"]+"|aria-label="([^"]+)")', source):
        found[m.group(1)] = m.group(2)
    for m in re.finditer(r'id="([^"]+)-title"[^>]*>(.*?)</h[12]>', source, re.S):
        found[m.group(1)] = re.sub(r"<[^>]+>", "", m.group(2))
    return {k: html.unescape(" ".join((v or k).split())).rstrip(".") for k, v in found.items()}


def main():
    captures = final_captures()
    if len(captures) < 2:
        sys.exit(f"No QA captures in {QA}; run npm test first.")
    names = titles()
    SLIDES_OUT.mkdir(parents=True, exist_ok=True)
    for stale in SLIDES_OUT.glob("*.*"):
        stale.unlink()

    rows, cols = -(-len(captures) // SHEET_COLS), SHEET_COLS
    sheet = Image.new("RGB", (cols * SHEET_CELL[0] + (cols + 1) * GAP, rows * SHEET_CELL[1] + (rows + 1) * GAP), (28, 28, 28))
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.load_default(size=14)
    cells = []
    for index, (number, slide_id, path) in enumerate(captures):
        image = Image.open(path).convert("RGB")
        name = f"{number:02d}-{slide_id}.jpg"
        image.resize(THUMB, Image.LANCZOS).save(SLIDES_OUT / name, quality=85, optimize=True)
        x = GAP + (index % cols) * (SHEET_CELL[0] + GAP)
        y = GAP + (index // cols) * (SHEET_CELL[1] + GAP)
        sheet.paste(image.resize(SHEET_CELL, Image.LANCZOS), (x, y))
        draw.rectangle((x, y, x + 30, y + 20), fill=(0, 0, 0))
        draw.text((x + 4, y + 2), f"{number}", fill=(150, 248, 255), font=font)
        cells.append((number, slide_id, name))
    sheet.save(OUT / "overview.jpg", quality=85, optimize=True)

    lines = [START, "", f"Generated by `npm run preview` from the QA captures ({len(cells)} slides, final fragment state). Select a thumbnail to open that slide in the [live deck]({LIVE}).", ""]
    lines += ["| | | |", "|---|---|---|"]
    for i in range(0, len(cells), 3):
        row = []
        for number, slide_id, name in cells[i:i + 3]:
            title = names.get(slide_id, slide_id).replace("|", "/")
            row.append(f"[![{number}. {title}](preview/slides/{name})]({LIVE}#/{slide_id})<br>**{number}.** {title}")
        row += [""] * (3 - len(row))
        lines.append("| " + " | ".join(row) + " |")
    lines += ["", END]
    block = "\n".join(lines)

    readme = README.read_text(encoding="utf-8")
    if START in readme and END in readme:
        readme = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, readme, flags=re.S)
    else:
        anchor = "## Open the presentation"
        section = f"## Preview\n\n[![Overview of all slides](preview/overview.jpg)]({LIVE})\n\n{block}\n\n"
        readme = readme.replace(anchor, section + anchor, 1) if anchor in readme else readme + "\n" + section
    README.write_text(readme, encoding="utf-8", newline="\n")
    print(f"Preview: {len(cells)} thumbnails, overview {sheet.size[0]}x{sheet.size[1]}, README gallery updated.")


if __name__ == "__main__":
    main()
